/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NavItem, Route } from "@/interfaces";
export namespace Components {
    interface AppNav {
        "items": NavItem[];
    }
    interface AppRoot {
    }
    interface AppRouter {
        "routes": Route[];
    }
    interface HomeView {
    }
    interface MoviesView {
    }
    interface TvshowsView {
    }
}
declare global {
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppRouterElement extends Components.AppRouter, HTMLStencilElement {
    }
    var HTMLAppRouterElement: {
        prototype: HTMLAppRouterElement;
        new (): HTMLAppRouterElement;
    };
    interface HTMLHomeViewElement extends Components.HomeView, HTMLStencilElement {
    }
    var HTMLHomeViewElement: {
        prototype: HTMLHomeViewElement;
        new (): HTMLHomeViewElement;
    };
    interface HTMLMoviesViewElement extends Components.MoviesView, HTMLStencilElement {
    }
    var HTMLMoviesViewElement: {
        prototype: HTMLMoviesViewElement;
        new (): HTMLMoviesViewElement;
    };
    interface HTMLTvshowsViewElement extends Components.TvshowsView, HTMLStencilElement {
    }
    var HTMLTvshowsViewElement: {
        prototype: HTMLTvshowsViewElement;
        new (): HTMLTvshowsViewElement;
    };
    interface HTMLElementTagNameMap {
        "app-nav": HTMLAppNavElement;
        "app-root": HTMLAppRootElement;
        "app-router": HTMLAppRouterElement;
        "home-view": HTMLHomeViewElement;
        "movies-view": HTMLMoviesViewElement;
        "tvshows-view": HTMLTvshowsViewElement;
    }
}
declare namespace LocalJSX {
    interface AppNav {
        "items"?: NavItem[];
    }
    interface AppRoot {
    }
    interface AppRouter {
        "routes"?: Route[];
    }
    interface HomeView {
    }
    interface MoviesView {
    }
    interface TvshowsView {
    }
    interface IntrinsicElements {
        "app-nav": AppNav;
        "app-root": AppRoot;
        "app-router": AppRouter;
        "home-view": HomeView;
        "movies-view": MoviesView;
        "tvshows-view": TvshowsView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-nav": LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-router": LocalJSX.AppRouter & JSXBase.HTMLAttributes<HTMLAppRouterElement>;
            "home-view": LocalJSX.HomeView & JSXBase.HTMLAttributes<HTMLHomeViewElement>;
            "movies-view": LocalJSX.MoviesView & JSXBase.HTMLAttributes<HTMLMoviesViewElement>;
            "tvshows-view": LocalJSX.TvshowsView & JSXBase.HTMLAttributes<HTMLTvshowsViewElement>;
        }
    }
}
